sudo: required

dist: xenial

language: python
python:
  - 3.6


matrix:
  include:
    - compiler: gcc
      before_install:
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -qq
      install:
        - sudo apt-get install -qq gcc-6
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90
        - pip install numpy
      before_script:
        - ./install-python.sh
      script:
        - python3 setup.py test

    - language: objective-c
      os: osx
      compiler: clang
      before_install:
        - brew install python3
        - python3 -m pip install numpy numba
      before_script:
        - export CC=clang
        - export CXX=clang++
        - ./install-python.sh
      script:
        - python3 setup.py test
